services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@host.docker.internal:5432/mydatabase
      - PORT=8080
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL=postgresql://postgres:123456@host.docker.internal:5432/mydatabase
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@host.docker.internal:5432/mydatabase
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@host.docker.internal:5432/mydatabase
