FROM node:23-alpine

RUN npm install -g pnpm@9.0.0

ARG DB_URL

WORKDIR /usr/src/app

COPY . .

RUN pnpm install

RUN pnpm run generate:db
RUN DB_URL=$DB_URL pnpm exec turbo build --filter=web...

EXPOSE 3000

CMD ["pnpm", "start:frontend"]
